"""Extract (mu, eta, kappa) from measured homodyne noise spectra.

The standard characterization of a below-threshold squeezer is a pair
of homodyne noise spectra versus analysis frequency: the squeezed
quadrature (a Lorentzian dip below shot noise) and the antisqueezed
quadrature (a Lorentzian peak above it).  This module fits the
package's own single-mode model to that pair and returns the pump
parameter mu, the total detection efficiency eta, and the cavity
linewidth kappa, with uncertainties.

Identifiability is arithmetic, not hope: one quadrature alone is a
single Lorentzian with exactly two shape numbers (depth and width) --
too few for the three unknowns, since the squeezed width reads
(1 + mu) kappa/2 and the depth mixes eta with mu.  The PAIR of
quadratures carries two independent widths, (1 + mu) kappa/2 and
(1 - mu) kappa/2, which separate mu from kappa, and the depths then
fix eta.  Accordingly the fit REQUIRES both spectra unless you pass a
known `kappa_hz` measured independently (e.g. from a linear cavity
scan), in which case one quadrature suffices.

The model curves are generated by `sqzcomb.spectra
.output_quadrature_variance` on `single_mode_parametric(mu)` -- the
same code path the rest of the package uses, cross-checked in the
package's tests against the closed form
S(Omega) = 1/2 [1 -/+ 4 eta mu / ((1 +/- mu)^2 + Omega^2)] -- with an
optional white dark-noise floor added in shot-noise units.  Input
spectra are in dB relative to shot noise (0 dB = vacuum), the way a
spectrum analyzer trace is calibrated.

Anchors asserted in the tests rather than stated: noise-free synthetic
spectra return the generating (mu, eta, kappa) to better than 1e-6;
the fitted model equals the independent closed form at every
frequency; seeded Monte-Carlo scatter matches the reported sigmas;
a single-quadrature fit without a known kappa is refused (the
degeneracy above), and refused loudly rather than returned with a
garbage covariance; and an antisqueezed trace below shot noise --
physically impossible for this model -- is refused.

Other models (new in 0.13). `fit_spectra_model` fits ANY model that
returns quadrature variances versus frequency, with the same least
squares, and checks identifiability instead of assuming it: the
Jacobian at the solution (each column scaled by its parameter's
size) must not be close to singular, otherwise the fit refuses and
names the parameter combination the data cannot pin down. Two ready
models are provided: `parametric_spectra_model` (the single-mode
model of `fit_noise_spectra`, optionally with a detuning, a phase
jitter of the local oscillator and a dark-noise floor) and
`molecule_spectra_model` (the two-ring `photonic_molecule`, read at
the main or the auxiliary ring's port).

Phase jitter (`jitter_average`) uses the exact fact that every
quadrature variance of a Gaussian state is V(phi) = c0 + c1 cos 2 phi
+ c2 sin 2 phi, so averaging over a Gaussian jitter of RMS sigma
shrinks the phi-dependent part by exp(-2 sigma^2): V_jit(phi) = Vbar
+ exp(-2 sigma^2) (V(phi) - Vbar), Vbar = (V(phi) + V(phi + pi/2)) / 2
(the same law as `phase_noise_variance`, for any angle).
"""
from __future__ import annotations

import dataclasses

import numpy as np
from scipy.optimize import least_squares

from .linearize import single_mode_parametric
from .spectra import output_quadrature_variance

__all__ = ["NoiseFit", "fit_noise_spectra", "noise_spectrum_db",
           "ModelFit", "fit_spectra_model", "parametric_spectra_model",
           "molecule_spectra_model", "jitter_average"]

_VAC = 0.5


def noise_spectrum_db(mu, eta, kappa_hz, f_hz, quadrature="squeezed",
                      dark=0.0):
    """Model spectrum in dB relative to shot noise at analysis
    frequencies f_hz (ordinary Hz), through the package's own
    input-output solver.  `dark` is a white noise floor in shot-noise
    variance units, added before the dB conversion."""
    f = np.atleast_1d(np.asarray(f_hz, dtype=float))
    kappa = 2.0 * np.pi * float(kappa_hz)
    om = 4.0 * np.pi * f / kappa                 # units of kappa/2
    M = single_mode_parametric(float(mu))
    phi = np.pi / 2.0 if quadrature == "squeezed" else 0.0
    v = np.array([output_quadrature_variance(M, float(eta), o, 0, 1,
                                             phi=phi) for o in om])
    v = v + float(dark)
    return 10.0 * np.log10(v / _VAC)


@dataclasses.dataclass
class NoiseFit:
    """Fitted squeezer parameters with uncertainties.

    mu : pump parameter (threshold at 1).
    eta : total detection efficiency (escape x propagation x quantum).
    kappa_hz : cavity linewidth (FWHM, ordinary Hz); equals the input
        when it was supplied as known.
    dark : fitted white dark-noise floor (shot-noise variance units),
        0 when not fitted.
    sigma : dict of one-standard-deviation uncertainties for the
        fitted parameters (absent keys were held fixed).
    chi2, chi2_dof : when measurement sigmas were provided.
    model_sq_db, model_anti_db : fitted model curves at the data
        frequencies (None for a quadrature not supplied).
    """

    mu: float
    eta: float
    kappa_hz: float
    dark: float
    sigma: dict
    chi2: float | None
    chi2_dof: int | None
    model_sq_db: np.ndarray | None
    model_anti_db: np.ndarray | None


def fit_noise_spectra(f_hz, sq_db=None, anti_db=None, sigma_db=None,
                      kappa_hz=None, fit_dark=False) -> NoiseFit:
    """Fit (mu, eta[, kappa, dark]) to measured noise spectra.

    f_hz : (n,) analysis frequencies (ordinary Hz, positive).
    sq_db, anti_db : the squeezed and antisqueezed traces in dB
        relative to shot noise (each (n,) or None).  Both are required
        unless `kappa_hz` is given (see module docstring: one
        Lorentzian cannot determine three parameters).
    sigma_db : optional scalar or per-point 1-sigma uncertainty of the
        traces (dB); enables the chi-square consistency check.
    kappa_hz : pass the independently measured linewidth to hold it
        fixed; otherwise it is fitted (both traces required).
    fit_dark : also fit a white dark-noise floor common to both
        traces.

    Raises ValueError on malformed input, on an antisqueezed trace
    below shot noise, and on the under-determined single-trace case.
    """
    f = np.asarray(f_hz, dtype=float).ravel()
    if f.size < 5 or np.any(f <= 0.0) or not np.all(np.isfinite(f)):
        raise ValueError("need >= 5 positive, finite analysis "
                         "frequencies")
    traces = []
    if sq_db is not None:
        sq = np.asarray(sq_db, dtype=float).ravel()
        if sq.shape != f.shape or not np.all(np.isfinite(sq)):
            raise ValueError("sq_db must match f_hz and be finite")
        traces.append(("squeezed", sq))
    if anti_db is not None:
        an = np.asarray(anti_db, dtype=float).ravel()
        if an.shape != f.shape or not np.all(np.isfinite(an)):
            raise ValueError("anti_db must match f_hz and be finite")
        # the model's antisqueezed mean is >= 0 dB everywhere, so a
        # trace SYSTEMATICALLY below shot noise is impossible; single
        # points may dip below through detector noise, so the check is
        # on the mean (a quarter-dB systematic deficit is beyond
        # shot-noise-calibration slop)
        if float(an.mean()) < -0.25:
            raise ValueError(
                "the antisqueezed quadrature cannot lie below shot "
                "noise in this model; check the trace assignment and "
                "the shot-noise calibration")
        traces.append(("anti", an))
    if not traces:
        raise ValueError("provide sq_db, anti_db, or both")
    if len(traces) == 1 and kappa_hz is None:
        raise ValueError(
            "one quadrature is a single Lorentzian -- two shape "
            "numbers for three unknowns (mu, eta, kappa). Supply both "
            "quadratures, or pass the independently measured kappa_hz")

    fit_kappa = kappa_hz is None
    if not fit_kappa:
        k_fix = float(kappa_hz)
        if not (np.isfinite(k_fix) and k_fix > 0.0):
            raise ValueError("kappa_hz must be finite and positive")

    if sigma_db is None:
        w = 1.0
    else:
        sig = np.broadcast_to(np.asarray(sigma_db, dtype=float),
                              f.shape).copy()
        if np.any(sig <= 0.0) or not np.all(np.isfinite(sig)):
            raise ValueError("sigma_db must be finite and positive")
        w = 1.0 / sig

    # parameter vector: [logit-free mu, eta, (log kappa), (dark)]
    names = ["mu", "eta"] + (["kappa_hz"] if fit_kappa else []) \
        + (["dark"] if fit_dark else [])
    lo = [1e-4, 1e-3] + ([1.0] if fit_kappa else []) \
        + ([0.0] if fit_dark else [])
    hi = [1.0 - 1e-6, 1.0] + ([1e12] if fit_kappa else []) \
        + ([10.0] if fit_dark else [])
    # starting guesses from the data themselves
    k0 = float(np.median(f)) if fit_kappa else k_fix
    p0 = [0.5, 0.5] + ([k0] if fit_kappa else []) \
        + ([0.0] if fit_dark else [])

    def unpack(p):
        mu, eta = p[0], p[1]
        i = 2
        if fit_kappa:
            kap, i = p[i], i + 1
        else:
            kap = k_fix
        dark = p[i] if fit_dark else 0.0
        return mu, eta, kap, dark

    def resid(p):
        mu, eta, kap, dark = unpack(p)
        r = []
        for kind, data in traces:
            m = noise_spectrum_db(mu, eta, kap, f, quadrature=kind,
                                  dark=dark)
            r.append(w * (m - data))
        return np.concatenate(r)

    res = least_squares(resid, p0, bounds=(lo, hi), xtol=1e-14,
                        ftol=1e-14, gtol=1e-14)
    if not res.success:
        raise RuntimeError(f"noise-spectrum fit failed: {res.message}")
    mu, eta, kap, dark = unpack(res.x)
    J = res.jac
    n_data = sum(t[1].size for t in traces)
    dof = n_data - len(res.x)
    try:
        cov = np.linalg.inv(J.T @ J)
    except np.linalg.LinAlgError:
        raise RuntimeError(
            "singular information matrix: the data do not determine "
            "the parameters (flat traces, or frequencies far from the "
            "cavity linewidth)")
    rss = float(2.0 * res.cost)
    if sigma_db is None:
        if dof < 1:
            raise ValueError("too few points to estimate uncertainties "
                             "without sigma_db")
        cov = cov * (rss / dof)
        chi2 = chi2_dof = None
    else:
        chi2, chi2_dof = rss, dof
    s = np.sqrt(np.diag(cov))
    sigma = {nm: float(sv) for nm, sv in zip(names, s)}
    msq = noise_spectrum_db(mu, eta, kap, f, "squeezed", dark) \
        if sq_db is not None else None
    man = noise_spectrum_db(mu, eta, kap, f, "anti", dark) \
        if anti_db is not None else None
    return NoiseFit(mu=float(mu), eta=float(eta), kappa_hz=float(kap),
                    dark=float(dark), sigma=sigma, chi2=chi2,
                    chi2_dof=chi2_dof, model_sq_db=msq,
                    model_anti_db=man)


# ----------------------------------------------------------------------
# General models (new in 0.13)


def jitter_average(v_phi, v_phi_perp, theta_rms):
    """Variance at LO angle phi averaged over Gaussian phase jitter.

    v_phi, v_phi_perp : the variances at phi and at phi + pi/2 (vacuum
        0.5; arrays allowed). Returns Vbar + exp(-2 theta^2)
        (v_phi - Vbar) with Vbar their mean (exact for any Gaussian
        state, see the module docstring).
    """
    t = float(theta_rms)
    if not (np.isfinite(t) and t >= 0.0):
        raise ValueError("theta_rms must be finite and >= 0")
    a = np.asarray(v_phi, dtype=float)
    b = np.asarray(v_phi_perp, dtype=float)
    mean = 0.5 * (a + b)
    return mean + np.exp(-2.0 * t * t) * (a - mean)


def parametric_spectra_model(detuned=False, jitter=False, dark=False):
    """Single-mode squeezer model for `fit_spectra_model`.

    Parameters of the returned model: mu (real gain, threshold 1),
    eta (total detection efficiency), kappa_hz (linewidth, FWHM in
    Hz), and optionally delta (detuning in units of kappa/2) and phi_sq
    (LO angle of the squeezed trace; the antisqueezed trace is read at
    phi_sq + pi/2) when detuned=True, theta_rms (LO phase jitter, rad)
    when jitter=True, and dark (white floor, shot-noise variance units)
    when dark=True. Without detuning the traces are read at phi = pi/2
    (squeezed) and 0 (antisqueezed), as in `fit_noise_spectra`.

    Returns (names, model) with model(p, f_hz) -> {"squeezed": V,
    "anti": V} (variances, vacuum 0.5).
    """
    names = ["mu", "eta", "kappa_hz"] + (["delta", "phi_sq"] if detuned
                                         else []) \
        + (["theta_rms"] if jitter else []) + (["dark"] if dark else [])

    def model(p, f_hz):
        om = 4.0 * np.pi * np.asarray(f_hz, dtype=float) / (
            2.0 * np.pi * float(p["kappa_hz"]))
        M = single_mode_parametric(float(p["mu"]),
                                   float(p.get("delta", 0.0)))
        ph = float(p["phi_sq"]) if detuned else np.pi / 2.0
        eta = float(p["eta"])
        v_sq = np.array([output_quadrature_variance(M, eta, o, 0, 1,
                                                    phi=ph) for o in om])
        v_an = np.array([output_quadrature_variance(
            M, eta, o, 0, 1, phi=ph + np.pi / 2.0) for o in om])
        if jitter:
            t = float(p["theta_rms"])
            v_sq, v_an = (jitter_average(v_sq, v_an, t),
                          jitter_average(v_an, v_sq, t))
        d = float(p.get("dark", 0.0))
        return {"squeezed": v_sq + d, "anti": v_an + d}

    return names, model


def molecule_spectra_model(port="aux", detuned=False):
    """Two-ring photonic molecule model for `fit_spectra_model`.

    Parameters: mu (gain on the main ring), J (inter-ring coupling),
    gamma (auxiliary ring decay), all in units of the main ring's
    kappa/2; eta (fraction of the monitored ring's decay reaching the
    detector); kappa_hz (main ring linewidth, FWHM in Hz).
    port : "main" (read at the main ring: squeezed at phi = pi/2) or
    "aux" (read at the auxiliary ring, where the hop turns the
    squeezed quadrature to phi = 0; see `photonic_molecule`).
    detuned : also delta_a, delta_b (detunings of the two rings) and
    phi_sq (LO angle of the squeezed trace; the antisqueezed trace is
    read at phi_sq + pi/2). Without it both detunings are 0 and the
    traces are read at the fixed angles above, which is only right
    for a molecule on resonance.
    """
    from .molecule import output_variance_ports, photonic_molecule
    if port not in ("main", "aux"):
        raise ValueError("port must be 'main' or 'aux'")
    names = ["mu", "J", "gamma", "eta", "kappa_hz"] + (
        ["delta_a", "delta_b", "phi_sq"] if detuned else [])
    pm = 0 if port == "main" else 1
    ph0 = np.pi / 2.0 if port == "main" else 0.0

    def model(p, f_hz):
        M, g = photonic_molecule(float(p["mu"]), float(p["J"]),
                                 float(p.get("delta_a", 0.0)),
                                 float(p.get("delta_b", 0.0)),
                                 float(p["gamma"]))
        om = 4.0 * np.pi * np.asarray(f_hz, dtype=float) / (
            2.0 * np.pi * float(p["kappa_hz"]))
        eta = float(p["eta"])
        ph_sq = float(p["phi_sq"]) if detuned else ph0
        v_sq = np.array([output_variance_ports(M, g, eta, pm, o,
                                               phi=ph_sq) for o in om])
        v_an = np.array([output_variance_ports(
            M, g, eta, pm, o, phi=ph_sq + np.pi / 2.0) for o in om])
        return {"squeezed": v_sq, "anti": v_an}

    return names, model


@dataclasses.dataclass
class ModelFit:
    """Result of `fit_spectra_model`.

    params : all parameters (fitted and fixed); sigma : 1-sigma
    uncertainties of the fitted ones; correlation : their correlation
    matrix (order of `fitted`); fitted : names of the fitted parameters;
    chi2, chi2_dof : with measurement sigmas; model_db : fitted curves
    (dB re shot noise) for each supplied trace.
    """

    params: dict
    sigma: dict
    correlation: np.ndarray
    fitted: list
    chi2: float | None
    chi2_dof: int | None
    model_db: dict


def fit_spectra_model(f_hz, data_db, model, names, p0, bounds=None,
                      fixed=None, sigma_db=None, cond_max=1e10,
                      n_starts=6, seed=0):
    """Least-squares fit of any spectrum model, with an
    identifiability check.

    f_hz : analysis frequencies (Hz, positive).
    data_db : dict trace-name -> measured trace in dB re shot noise
        (e.g. {"squeezed": ..., "anti": ...}); the model must return the
        same names.
    model, names : from `parametric_spectra_model`,
        `molecule_spectra_model`, or your own function
        model(params_dict, f_hz) -> dict of variances (vacuum 0.5).
    p0 : dict of starting values for every parameter not in `fixed`.
    bounds : dict name -> (low, high) (default unbounded).
    fixed : dict name -> value for parameters held fixed.
    sigma_db : scalar or per-point 1-sigma of the traces (dB).
    cond_max : largest allowed condition number of the scaled
        information matrix; beyond it the data do not determine the
        parameters separately and the fit refuses.
    n_starts, seed : the fit is repeated from p0 and from n_starts - 1
        seeded random starting points (uniform inside finite bounds,
        log-uniform for wide positive ranges, a factor of about e^0.5
        around p0 otherwise). If two starts end on fits that are
        equally good but clearly different, the data admit more than
        one answer (a discrete ambiguity that no local error bar can
        show) and the fit refuses, listing them.
    """
    f = np.asarray(f_hz, dtype=float).ravel()
    if f.size < 3 or np.any(f <= 0.0) or not np.all(np.isfinite(f)):
        raise ValueError("need >= 3 positive, finite analysis "
                         "frequencies")
    fixed = dict(fixed or {})
    bounds = dict(bounds or {})
    free = [nm for nm in names if nm not in fixed]
    missing = [nm for nm in free if nm not in p0]
    if missing:
        raise ValueError(f"no starting value for {missing}")
    unknown = [nm for nm in list(fixed) + list(p0) if nm not in names]
    if unknown:
        raise ValueError(f"not parameters of this model: {unknown}")
    if not data_db:
        raise ValueError("provide at least one trace")
    data = {}
    for k, v in data_db.items():
        arr = np.asarray(v, dtype=float).ravel()
        if arr.shape != f.shape or not np.all(np.isfinite(arr)):
            raise ValueError(f"trace {k!r} must match f_hz and be finite")
        data[k] = arr
    n_data = f.size * len(data)
    if n_data <= len(free):
        raise ValueError("more free parameters than data points")
    if sigma_db is None:
        w = 1.0
    else:
        sig = np.broadcast_to(np.asarray(sigma_db, dtype=float),
                              f.shape).copy()
        if np.any(sig <= 0.0) or not np.all(np.isfinite(sig)):
            raise ValueError("sigma_db must be finite and positive")
        w = 1.0 / sig
    lo = [bounds.get(nm, (-np.inf, np.inf))[0] for nm in free]
    hi = [bounds.get(nm, (-np.inf, np.inf))[1] for nm in free]
    x0 = np.array([float(p0[nm]) for nm in free])
    scale = np.where(np.abs(x0) > 0, np.abs(x0), 1.0)

    def full(x):
        p = dict(fixed)
        p.update(zip(free, x * scale))
        return p

    def resid(x):
        p = full(x)
        try:
            out = model(p, f)
        except ValueError:
            # outside the model's physical domain (e.g. unstable): a
            # large constant penalty keeps the optimizer away
            return np.full(n_data, 1e6)
        r = []
        for k in data:
            v = np.asarray(out[k], dtype=float)
            if np.any(v <= 0):
                return np.full(n_data, 1e6)
            r.append(w * (10.0 * np.log10(v / _VAC) - data[k]))
        return np.concatenate(r)

    lo_s, hi_s = np.array(lo) / scale, np.array(hi) / scale
    rng = np.random.default_rng(int(seed))
    starts = [x0 / scale]
    for _ in range(max(int(n_starts), 1) - 1):
        x = np.empty(len(free))
        for i in range(len(free)):
            a, b = lo[i], hi[i]
            if np.isfinite(a) and np.isfinite(b):
                if a > 0 and b / a > 100:
                    x[i] = np.exp(rng.uniform(np.log(a), np.log(b)))
                else:
                    x[i] = rng.uniform(a, b)
            else:
                x[i] = x0[i] * np.exp(rng.normal(0.0, 0.5)) if x0[i] \
                    else rng.normal(0.0, 1.0)
            x[i] = min(max(x[i], a), b)
        starts.append(x / scale)
    runs = []
    for xs in starts:
        xs = np.clip(xs, lo_s, hi_s)
        r = least_squares(resid, xs, bounds=(lo_s, hi_s), xtol=1e-15,
                          ftol=1e-15, gtol=1e-15, x_scale="jac")
        if r.success and np.all(np.isfinite(r.x)):
            runs.append(r)
    if not runs:
        raise RuntimeError("spectrum fit failed from every start")
    runs.sort(key=lambda r: r.cost)
    res = runs[0]
    J = res.jac                                # in scaled coordinates
    sv = np.linalg.svd(J, compute_uv=False)
    if sv[-1] <= 0 or (sv[0] / sv[-1]) ** 2 > float(cond_max):
        _, _, Vt = np.linalg.svd(J)
        weak = Vt[-1]
        order = np.argsort(np.abs(weak))[::-1]
        combo = ", ".join(f"{weak[i]:+.2f} {free[i]}" for i in order
                          if abs(weak[i]) > 0.1)
        raise ValueError(
            "the data do not determine these parameters separately "
            f"(the combination [{combo}] is unconstrained). Fix some "
            "parameters from independent measurements, or add traces "
            "or frequencies that separate them")
    cov = np.linalg.inv(J.T @ J)
    rss = float(2.0 * res.cost)
    dof = n_data - len(free)
    if sigma_db is None:
        cov = cov * (rss / dof)
        chi2 = chi2_dof = None
    else:
        chi2, chi2_dof = rss, dof
    cov = cov * np.outer(scale, scale)
    sd = np.sqrt(np.diag(cov))
    best = res.x * scale
    tol_cost = 1e-6 * res.cost + 1e-20 * n_data
    alts = []
    for r in runs[1:]:
        if r.cost - res.cost > tol_cost:
            continue
        other = r.x * scale
        gap = np.abs(other - best)
        if np.any(gap > np.maximum(3.0 * sd, 1e-6 * np.abs(best) + 1e-12)):
            alts.append(other)
    if alts:
        show = "; ".join(
            "{" + ", ".join(f"{nm}={v:.6g}" for nm, v in zip(free, x)) + "}"
            for x in [best] + alts[:2])
        raise ValueError(
            "the data are fitted equally well by clearly different "
            f"parameter sets: {show}. The measurement cannot decide "
            "between them; fix a parameter from an independent "
            "measurement or add data that separates them")
    den = np.outer(sd, sd)
    corr = np.divide(cov, den, out=np.zeros_like(cov), where=den > 0)
    np.fill_diagonal(corr, 1.0)
    params = full(res.x)
    out = model(params, f)
    return ModelFit(params={k: float(v) for k, v in params.items()},
                    sigma={nm: float(v) for nm, v in zip(free, sd)},
                    correlation=corr, fitted=free, chi2=chi2,
                    chi2_dof=chi2_dof,
                    model_db={k: 10.0 * np.log10(np.asarray(out[k])
                                                 / _VAC) for k in data})
