"""Extract (mu, eta, kappa) from measured homodyne noise spectra.

The standard characterization of a below-threshold squeezer is a pair
of homodyne noise spectra versus analysis frequency: the squeezed
quadrature (a Lorentzian dip below shot noise) and the antisqueezed
quadrature (a Lorentzian peak above it).  This module fits the
package's own single-mode model to that pair and returns the pump
parameter mu, the total detection efficiency eta, and the cavity
linewidth kappa, with uncertainties.

Identifiability is arithmetic, not hope: one quadrature alone is a
single Lorentzian with exactly two shape numbers (depth and width) --
too few for the three unknowns, since the squeezed width reads
(1 + mu) kappa/2 and the depth mixes eta with mu.  The PAIR of
quadratures carries two independent widths, (1 + mu) kappa/2 and
(1 - mu) kappa/2, which separate mu from kappa, and the depths then
fix eta.  Accordingly the fit REQUIRES both spectra unless you pass a
known `kappa_hz` measured independently (e.g. from a linear cavity
scan), in which case one quadrature suffices.

The model curves are generated by `sqzcomb.spectra
.output_quadrature_variance` on `single_mode_parametric(mu)` -- the
same code path the rest of the package uses, cross-checked in the
package's tests against the closed form
S(Omega) = 1/2 [1 -/+ 4 eta mu / ((1 +/- mu)^2 + Omega^2)] -- with an
optional white dark-noise floor added in shot-noise units.  Input
spectra are in dB relative to shot noise (0 dB = vacuum), the way a
spectrum analyzer trace is calibrated.

Anchors asserted in the tests rather than stated: noise-free synthetic
spectra return the generating (mu, eta, kappa) to better than 1e-6;
the fitted model equals the independent closed form at every
frequency; seeded Monte-Carlo scatter matches the reported sigmas;
a single-quadrature fit without a known kappa is refused (the
degeneracy above), and refused loudly rather than returned with a
garbage covariance; and an antisqueezed trace below shot noise --
physically impossible for this model -- is refused.
"""
from __future__ import annotations

import dataclasses

import numpy as np
from scipy.optimize import least_squares

from .linearize import single_mode_parametric
from .spectra import output_quadrature_variance

__all__ = ["NoiseFit", "fit_noise_spectra", "noise_spectrum_db"]

_VAC = 0.5


def noise_spectrum_db(mu, eta, kappa_hz, f_hz, quadrature="squeezed",
                      dark=0.0):
    """Model spectrum in dB relative to shot noise at analysis
    frequencies f_hz (ordinary Hz), through the package's own
    input-output solver.  `dark` is a white noise floor in shot-noise
    variance units, added before the dB conversion."""
    f = np.atleast_1d(np.asarray(f_hz, dtype=float))
    kappa = 2.0 * np.pi * float(kappa_hz)
    om = 4.0 * np.pi * f / kappa                 # units of kappa/2
    M = single_mode_parametric(float(mu))
    phi = np.pi / 2.0 if quadrature == "squeezed" else 0.0
    v = np.array([output_quadrature_variance(M, float(eta), o, 0, 1,
                                             phi=phi) for o in om])
    v = v + float(dark)
    return 10.0 * np.log10(v / _VAC)


@dataclasses.dataclass
class NoiseFit:
    """Fitted squeezer parameters with uncertainties.

    mu : pump parameter (threshold at 1).
    eta : total detection efficiency (escape x propagation x quantum).
    kappa_hz : cavity linewidth (FWHM, ordinary Hz); equals the input
        when it was supplied as known.
    dark : fitted white dark-noise floor (shot-noise variance units),
        0 when not fitted.
    sigma : dict of one-standard-deviation uncertainties for the
        fitted parameters (absent keys were held fixed).
    chi2, chi2_dof : when measurement sigmas were provided.
    model_sq_db, model_anti_db : fitted model curves at the data
        frequencies (None for a quadrature not supplied).
    """

    mu: float
    eta: float
    kappa_hz: float
    dark: float
    sigma: dict
    chi2: float | None
    chi2_dof: int | None
    model_sq_db: np.ndarray | None
    model_anti_db: np.ndarray | None


def fit_noise_spectra(f_hz, sq_db=None, anti_db=None, sigma_db=None,
                      kappa_hz=None, fit_dark=False) -> NoiseFit:
    """Fit (mu, eta[, kappa, dark]) to measured noise spectra.

    f_hz : (n,) analysis frequencies (ordinary Hz, positive).
    sq_db, anti_db : the squeezed and antisqueezed traces in dB
        relative to shot noise (each (n,) or None).  Both are required
        unless `kappa_hz` is given (see module docstring: one
        Lorentzian cannot determine three parameters).
    sigma_db : optional scalar or per-point 1-sigma uncertainty of the
        traces (dB); enables the chi-square consistency check.
    kappa_hz : pass the independently measured linewidth to hold it
        fixed; otherwise it is fitted (both traces required).
    fit_dark : also fit a white dark-noise floor common to both
        traces.

    Raises ValueError on malformed input, on an antisqueezed trace
    below shot noise, and on the under-determined single-trace case.
    """
    f = np.asarray(f_hz, dtype=float).ravel()
    if f.size < 5 or np.any(f <= 0.0) or not np.all(np.isfinite(f)):
        raise ValueError("need >= 5 positive, finite analysis "
                         "frequencies")
    traces = []
    if sq_db is not None:
        sq = np.asarray(sq_db, dtype=float).ravel()
        if sq.shape != f.shape or not np.all(np.isfinite(sq)):
            raise ValueError("sq_db must match f_hz and be finite")
        traces.append(("squeezed", sq))
    if anti_db is not None:
        an = np.asarray(anti_db, dtype=float).ravel()
        if an.shape != f.shape or not np.all(np.isfinite(an)):
            raise ValueError("anti_db must match f_hz and be finite")
        # the model's antisqueezed mean is >= 0 dB everywhere, so a
        # trace SYSTEMATICALLY below shot noise is impossible; single
        # points may dip below through detector noise, so the check is
        # on the mean (a quarter-dB systematic deficit is beyond
        # shot-noise-calibration slop)
        if float(an.mean()) < -0.25:
            raise ValueError(
                "the antisqueezed quadrature cannot lie below shot "
                "noise in this model; check the trace assignment and "
                "the shot-noise calibration")
        traces.append(("anti", an))
    if not traces:
        raise ValueError("provide sq_db, anti_db, or both")
    if len(traces) == 1 and kappa_hz is None:
        raise ValueError(
            "one quadrature is a single Lorentzian -- two shape "
            "numbers for three unknowns (mu, eta, kappa). Supply both "
            "quadratures, or pass the independently measured kappa_hz")

    fit_kappa = kappa_hz is None
    if not fit_kappa:
        k_fix = float(kappa_hz)
        if not (np.isfinite(k_fix) and k_fix > 0.0):
            raise ValueError("kappa_hz must be finite and positive")

    if sigma_db is None:
        w = 1.0
    else:
        sig = np.broadcast_to(np.asarray(sigma_db, dtype=float),
                              f.shape).copy()
        if np.any(sig <= 0.0) or not np.all(np.isfinite(sig)):
            raise ValueError("sigma_db must be finite and positive")
        w = 1.0 / sig

    # parameter vector: [logit-free mu, eta, (log kappa), (dark)]
    names = ["mu", "eta"] + (["kappa_hz"] if fit_kappa else []) \
        + (["dark"] if fit_dark else [])
    lo = [1e-4, 1e-3] + ([1.0] if fit_kappa else []) \
        + ([0.0] if fit_dark else [])
    hi = [1.0 - 1e-6, 1.0] + ([1e12] if fit_kappa else []) \
        + ([10.0] if fit_dark else [])
    # starting guesses from the data themselves
    k0 = float(np.median(f)) if fit_kappa else k_fix
    p0 = [0.5, 0.5] + ([k0] if fit_kappa else []) \
        + ([0.0] if fit_dark else [])

    def unpack(p):
        mu, eta = p[0], p[1]
        i = 2
        if fit_kappa:
            kap, i = p[i], i + 1
        else:
            kap = k_fix
        dark = p[i] if fit_dark else 0.0
        return mu, eta, kap, dark

    def resid(p):
        mu, eta, kap, dark = unpack(p)
        r = []
        for kind, data in traces:
            m = noise_spectrum_db(mu, eta, kap, f, quadrature=kind,
                                  dark=dark)
            r.append(w * (m - data))
        return np.concatenate(r)

    res = least_squares(resid, p0, bounds=(lo, hi), xtol=1e-14,
                        ftol=1e-14, gtol=1e-14)
    if not res.success:
        raise RuntimeError(f"noise-spectrum fit failed: {res.message}")
    mu, eta, kap, dark = unpack(res.x)
    J = res.jac
    n_data = sum(t[1].size for t in traces)
    dof = n_data - len(res.x)
    try:
        cov = np.linalg.inv(J.T @ J)
    except np.linalg.LinAlgError:
        raise RuntimeError(
            "singular information matrix: the data do not determine "
            "the parameters (flat traces, or frequencies far from the "
            "cavity linewidth)")
    rss = float(2.0 * res.cost)
    if sigma_db is None:
        if dof < 1:
            raise ValueError("too few points to estimate uncertainties "
                             "without sigma_db")
        cov = cov * (rss / dof)
        chi2 = chi2_dof = None
    else:
        chi2, chi2_dof = rss, dof
    s = np.sqrt(np.diag(cov))
    sigma = {nm: float(sv) for nm, sv in zip(names, s)}
    msq = noise_spectrum_db(mu, eta, kap, f, "squeezed", dark) \
        if sq_db is not None else None
    man = noise_spectrum_db(mu, eta, kap, f, "anti", dark) \
        if anti_db is not None else None
    return NoiseFit(mu=float(mu), eta=float(eta), kappa_hz=float(kap),
                    dark=float(dark), sigma=sigma, chi2=chi2,
                    chi2_dof=chi2_dof, model_sq_db=msq,
                    model_anti_db=man)
